language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local_dir: build
  default_text_charset: "utf-8"
  bucket: "pixelstir.com"
  region: "us-east-1"
  local_dir: build